"""add_card_interactions_and_spaced_reviews

Revision ID: e3c02cf4c22e
Revises: 
Create Date: 2026-02-27 16:48:48.109980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3c02cf4c22e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaced_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.String(length=200), nullable=False),
    sa.Column('review_number', sa.SmallInteger(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.String(length=200), nullable=False),
    sa.Column('card_index', sa.Integer(), nullable=False),
    sa.Column('time_on_card_sec', sa.Float(), nullable=False),
    sa.Column('wrong_attempts', sa.Integer(), nullable=False),
    sa.Column('selected_wrong_option', sa.SmallInteger(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('idle_triggers', sa.Integer(), nullable=False),
    sa.Column('adaptation_applied', sa.String(length=200), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('teaching_sessions', 'lesson_interests',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teaching_sessions', 'lesson_interests',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_table('card_interactions')
    op.drop_table('spaced_reviews')
    # ### end Alembic commands ###
